### ISSUE TITLE
[Feature Request] Sync word list from here.

### ISSUE THREAD

**Issue by esttorhe** [Palleas/NaughtyKeyboard#2]
Would be interesting if the app had some sort of `sync` mechanism to download the latest version from the repo.

This way people could `PR` new «naughty» strings and testers could easily and fairly quickly update the list without having to re-deploy the keyboard to their devices.

PS. I haven't looked at the current implementation; meaning I don't know if the keyboard already supports this.
PS2. If not I'll try to submit a `PR` with this behavior later this week

:bow:

**Comment by Palleas** [comment]
Right now the JSON file is embedded in the Keyboard target, that's definitely not optimal. 
You're more than welcome to propose something but ideally I think it should be performed by the main application and downloaded in a shared app container, don't you think?

**Comment by esttorhe** [comment]
Yes; definitely what I was thinking about; that's why I referred to the `app` instead of the `keyboard`.

I'll try to play with the concept this week

**Comment by Palleas** [comment]
:+1:
